###### ENDPOINTS EDIFICIO #############

### Obtener edificios
GET http://localhost:3002/api/edificio?nombre=torre

### Buscar por nombre (Este debería desaparecer)
GET http://localhost:3002/api/edificio/buscar/nombre?nombre=torre


