###### ENDPOINTS EMPRESA #############

### Obtener empresas
GET http://localhost:3002/api/empresa

### Obtener empresas por id (soporta por nombre y por id)
GET http://localhost:3002/api/empresa?idEmpresa=2

### Buscar por nombre (este debería desaparecer)
GET http://localhost:3002/api/empresa/buscar/nombre?nombre=siem

