############################ facturaCompra ############################

### GET facturaCompra
GET http://localhost:3002/api/facturaCompra?idObra=1212

### GET FACTURA BY ID 
GET http://localhost:3002/api/facturaCompra/209

### GET facturaCompra BY OBRAS (Debería desaparecer)
GET http://localhost:3002/api/facturaCompra/obra/1503

### GET BY CONCEPTO (Debería desaparecer)
GET http://localhost:3002/api/facturaCompra/buscar/concepto?concepto=SAMSUNG

### NUEVA FACTURA
POST http://localhost:3002/api/facturaCompra/209
Content-Type: application/json

{
    "codigoUsuarioAlta": 67,
    "fechaAlta": "2026-02-11",
    "idfacturaCompraCompras": 313,
    "idObra": 1503,
    "importe": "12",
    "observaciones": "Esta es una compra de prueba"
}

### ACTUALIZAR FACTURA
PATCH  http://localhost:3002/api/facturaCompra/3
Content-Type: application/json

{
    "observaciones": "Observaciones actualizadas"               
}

### DELETE FACTURA

DELETE http://localhost:3002/facturaCompra/15