###### ENDPOINTS GASTOS #############

### Obtener todos los gastos 
GET http://localhost:3002/api/gastos

### Obtener todos los gastos por pagar
GET http://localhost:3002/api/gastos/por-pagar

### Obtener todos los gastos de una obra (Debería desaparecer)
POST http://localhost:3002/api/gastos/buscar
Content-Type: application/json

{
    "idsObra": [4039]
}

### Obtener el listado de horas extra de una obra (Debería desaparecer)
POST http://localhost:3002/api/gastos/horas-extra/buscar
Content-Type: application/json

{
    "idsObra": [4039]
}


### Obtener un gasto aplicando filtros (Este es el que se queda). 
POST http://localhost:3002/api/gastos/filtrar
Content-Type: application/json

{
    "idsObra": [1212],
    "tipoGasto": "Hora Extra"

}


