###### ENDPOINTS HORAS #############

### Obtener el listado de horas asociado a una obra
POST http://localhost:3002/api/horas/filtrar
Content-Type: application/json

{
    "idsObra": [4037],
    "manager": 4
}

### Crear una hora
POST http://localhost:3002/api/horas
Content-Type: application/json

{
    "diaTrabajado": "2026-02-10",
    "usuarioAsignado": 67,
    "obraAsignada": 133,
    "tareaAsignada": 1,
    "horasAsignadas": 8,
    "observaciones": "Hora de prueba para probar POST"
}


### Obtener el listado de todas las horas (Es muy lenta esta consulta si no se aplica limit)
GET http://localhost:3002/api/horas?limit=10