###### ENDPOINTS PEDIDOS #############

### Obtener un pedido
GET http://localhost:3002/api/pedidoObra/50

### Obtener pedidos asociados a una obra
POST http://localhost:3002/api/pedidoObra/filtrar
Content-Type: application/json

{
    "idsObra": [1212]
}

### Borrar un pedido asociado a una obra
DELETE http://localhost:3002/api/pedidoObra/4861
Content-Type: application/json

{
    "codigoUsuarioBaja": 4
}