###### ENDPOINTS EMPRESA #############

### Obtener proveedores
GET http://localhost:3002/api/proveedor

### Obtener empresas por id (soporta por nombre y por id de momento)
GET http://localhost:3002/api/empresa?idEmpresa=61

### Crear una empresa
POST http://localhost:3002/api/empresa
Content-Type: application/json

{
    "nombre": "Empresa de pruebas 2",
    "cif": "00000001",
    "tipoEmpresa": 1,
    "direccion": "Dirección Inventada",
    "poblacion": "Madrid",
    "provincia": "Madrid",
    "cp": "28043",
    "telefono1": "",
    "telefono2": "",
    "fax": "",
    "email": "empresaPrueba2@gmail.com",
    "evaluacion": 0,
    "observaciones": "Esta es una segunda empresa de prueba para probar el POST",
    "mostrarSaldo": 0,
    "porDefecto": 0,
    "contactos": [83, 84, 82, 85]
}

### Actualizar una empresa 
PATCH http://localhost:3002/api/empresa/62
Content-Type: application/json

{
    "observaciones": "Actualización en las observaciones para probar el PATCH",
    "contactos": [83, 84, 85]
    
}

### Dar de baja empresas
DELETE http://localhost:3002/api/empresa
Content-Type: application/json

{
    "idEmpresas": [61, 62]
}

### Buscar por nombre (este debería desaparecer)
GET http://localhost:3002/api/empresa/buscar/nombre?nombre=siem

