###### ENDPOINTS EMPRESA #############

### Obtener proveedores
GET http://localhost:3002/api/proveedor

### Obtener proveedores aplicando filtros
GET http://localhost:3002/api/proveedor?nombre=abac

### Crear una proveedor
POST http://localhost:3002/api/proveedor
Content-Type: application/json

{
    "codigo": "50432",
    "nombre": "Proveedor de Pruebas",
    "cif": "B123456789",
    "contacto": "Pepe Pruebas",
    "direccion": "Dirección Inventada",
    "poblacion": "Madrid",
    "provincia": "Madrid",
    "cp": "28001",
    "telefono1": "888-888-888",
    "email": "tuproveedordeconfianza@gmail.com",
    "observaciones": "Este es un proveedor de pruebas"
}

### Actualizar un proveedor 
PATCH http://localhost:3002/api/proveedor/2088
Content-Type: application/json

{
    "observaciones": "Actualización en las observaciones para probar el PATCH"
}

### Dar de baja proveedor
DELETE http://localhost:3002/api/proveedor
Content-Type: application/json

{
    "idProveedores": [2088]
}

