############################ FACTURAS ############################

### GET FACTURAS
GET http://localhost:3002/api/facturas

### GET FACTURA BY ID
GET http://localhost:3002/api/facturas/209

### GET FACTURAS BY OBRAS
GET http://localhost:3002/api/facturas/obra/1503

### GET BY CONCEPTO
GET http://localhost:3002/api/facturas/buscar/concepto?concepto=SAMSUNG

### NUEVA FACTURA
POST http://localhost:3002/api/facturas/209
Content-Type: application/json

{
    "codigoUsuarioAlta": 67,
    "fechaAlta": "2025-10-09",
    "idFacturasCompras": 313,
    "idObra": 1503,
    "importe": "12",
    "observaciones": "Esta es una compra de prueba"
}

### ACTUALIZAR FACTURA
PATCH  http://localhost:3002/api/facturas/3
Content-Type: application/json

{
    "observaciones": "Observaciones actualizadas"               
}

### DELETE FACTURA

DELETE http://localhost:3002/facturas/15

############################ OBRAS ############################

### GET Obras
GET http://localhost:3002/api/obra

### GET Obra específica
GET http://localhost:3002/api/obra/1503

### GET Obras por descripción
GET http://localhost:3002/api/obra/buscar/descripcion?descripcionObra=Cambio

### POST Obra
POST http://localhost:3002/api/obra
Content-Type: application/json

{
  "cod": "3816C10219P0007M003-R0",
  "contacto": 1,
  "desc": "CNIO suministro PXC100",
  "descSeg": null,
  "edificio": 47,
  "empresa": 1,
  "estadoObra": 4,
  "facturable": 2,
  "fechaAlta": "2022-06-16",
  "fechaFin": null,
  "fechaOferta": "2022-06-16",
  "fechaSeg": null,
  "gastoPrevisto": 1106,
  "horasPrevistas": 0,
  "importe": 1327.19,
  "observaciones": "",
  "observacionesInternas": "PROPIEDAD: CNIO\nGestor Att.: Alejandro Aguilera\n",
  "tipoObra": 10,
  "usuarioAlta": 10,
  "viabilidad": 100
}


### Actualizar obra
PUT http://localhost:3002/api/obra/5303
Content-Type: application/json

{
    "estadoObra": 4
}

### Eliminar obra
DELETE http://localhost:3002/api/obra/5302
Content-Type: application/json

{
    "codigoUsuarioBaja": 4
}

### ENDPOINTS PARA LOS FORMS

### TIPOS DE OBRA
GET http://localhost:3002/api/tipos-obra


###### ENDPOINTS ALMACEN #############

### Obtener todos los productos
GET http://localhost:3002/api/almacen

### Obtener un producto específico
GET http://localhost:3002/api/almacen/1

### Obtener un producto por la descripción
GET http://localhost:3002/api/almacen/buscar/descripcion?descripcion=cable

### Crear un producto
POST http://localhost:3002/api/almacen
Content-Type: application/json

{
  "cod": "123456",
  "descripcion": "Material de prueba",
  "etiqueta": "uds.",
  "proveedor": 850,
  "familia": 2,
  "tipoUnidad": 3,
  "fechaAlta": "2016-06-21",
  "usuarioAlta": 4,
  "stock": 20,
  "stockMin": 3,
  "stockMax": 1000,
  "marca": 1,
  "precioUnitario": 1,
  "precioTotal": 4,
  "observaciones": "Material de prueba"
}

### Actualizar un producto
PUT http://localhost:3002/api/almacen/244
Content-Type: application/json

{
  "cod": "123456",
  "descripcion": "Material de prueba",
  "etiqueta": "uds.",
  "proveedor": 850,
  "familia": 2,
  "tipoUnidad": 3,
  "fechaAlta": "2016-06-21",
  "usuarioAlta": 4,
  "stock": 20,
  "stockMin": 3,
  "stockMax": 1000,
  "marca": 1,
  "precioUnitario": 1,
  "precioTotal": 4,
  "observaciones": "Observaciones actualizadas"
}

### Borrar un producto
DELETE http://localhost:3002/api/almacen/244
Content-Type: application/json

{
    "codigoUsuarioBaja": 14
}

###### ENDPOINTS CONTACTO #############

### Obtener contacto por id de empresa
GET http://localhost:3002/api/contacto/2

### Obtener todos los contactos
GET http://localhost:3002/api/contacto

###### ENDPOINTS EDIFICIO #############

### Obtener edificios
GET http://localhost:3002/api/edificio

###### ENDPOINTS EMPRESA #############

### Obtener empresas
GET http://localhost:3002/api/empresa

###### ENDPOINTS ESTADO OBRA #############

### Obtener estados obra
GET http://localhost:3002/api/estado-obra

###### ENDPOINTS TIPO FACTURABLE #############

### Obtener tipos facturable
GET http://localhost:3002/api/tipo-facturable

###### ENDPOINTS TIPO OBRA #############

### Obtener tipos obra
GET http://localhost:3002/api/tipo-obra

###### ENDPOINTS USUARIO #############

### Obtener usuarios
GET http://localhost:3002/api/usuario

### post para el login
POST http://localhost:3002/api/usuario/login
Content-Type: application/json

{
    "username": "abaco_andres",
    "password": "abaco_andres"
}


###### ENDPOINTS RELACION - OBRAS #############

### Obtener padre de una obra
GET http://localhost:3002/api/relacion-obras/padre/4733

### Obtener hijas de una obra
GET http://localhost:3002/api/relacion-obras/hijas/4039

### Establecer un padre a una obra
POST http://localhost:3002/api/relacion-obras/padre
Content-Type: application/json

{
    "idObraPadre": null,
    "idObraHija":2
}

### Establecer hijas a una obra
POST http://localhost:3002/api/relacion-obras/hijas
Content-Type: application/json

{
    "idObraPadre" : 1,
    "idsObrasHijas" : []
}

###### ENDPOINTS RENTABILIDAD #############

### Obtener rentabilidad
GET http://localhost:3002/api/rentabilidad/4758

###### ENDPOINTS ECOPEDIDOS #############

### Obtener pedidos asociados a una obra
POST http://localhost:3002/api/ecoPedido/buscar
Content-Type: application/json

{
    "idsObras": [4037]
}

### Borrar un pedido asociado a una obra
DELETE http://localhost:3002/api/ecoPedido/4861
Content-Type: application/json

{
    "codigoUsuarioBaja": 4
}


###### ENDPOINTS ECOFACTURAS #############

### Obtener facturas asociadas a una obra
POST http://localhost:3002/api/ecoFactura/buscar
Content-Type: application/json

{
    "idsObras": [4037]
}

### Crear una factura asociada a una obra
POST http://localhost:3002/api/ecoFactura/
Content-Type: application/json

{
    "idPedido": 6,
    "fechaFactura": "2016-06-21",
    "codigo": "FACTURAPRUEBA",
    "posicion": 10,
    "importe": 100,
    "conceptoFactura": "Factura de prueba",
    "conceptoLinea": "Factura de prueba",
    "observaciones": "Esta es una factura de prueba",
    "idObra": 4037
}

### Actualizar una factura asociada a una obra
PUT http://localhost:3002/api/ecoFactura/5377
Content-Type: application/json

{
    "idPedido": 6,
    "fechaFactura": "2016-06-21",
    "codigo": "FACTURAPRUEBA2",
    "posicion": 10,
    "importe": 100,
    "conceptoFactura": "Factura de prueba",
    "conceptoLinea": "Factura de prueba",
    "observaciones": "He actualizado la factura",
    "idObra": 4037
}

### Borrar una factura asociada a una obra
DELETE http://localhost:3002/api/ecoFactura/5376
Content-Type: application/json

{
    "codigoUsuarioBaja": 4
}

###### ENDPOINTS GASTOS #############

### Obtener todos los gastos por validar
GET http://localhost:3002/api/gastos/por-validar

### Obtener todos los gastos por pagar
GET http://localhost:3002/api/gastos/por-pagar

### Obtener todos los gastos de una obra
POST http://localhost:3002/api/gastos/buscar
Content-Type: application/json

{
    "idsObra": [4463]
}

### Obtener el listado de horas extra de una obra
POST http://localhost:3002/api/gastos/horas-extra/buscar
Content-Type: application/json

{
    "idsObra": [4039]
}

###### ENDPOINTS HORAS #############

### Obtener el listado de horas asociado a una obra
POST http://localhost:3002/api/horas/buscar
Content-Type: application/json

{
    "idsObra": [4037]
}

### Obtener el listado de todas las horas
GET http://localhost:3002/api/horas/all

###### ENDPOINTS MOVIMIENTOS ALMACEN #############

### Obtener el listado de movimientos del almacén asociado a una obra
GET http://localhost:3002/api/movimientos-almacen/obra/1232

###### ENDPOINTS USUARIOS #############

### Obtener todos los usuarios
GET http://localhost:3002/api/usuario

### Login
POST http://localhost:3002/api/usuario/login
Content-Type: application/json

{
    "username": "abaco_andres",
    "password": "abaco_andres"
}